# Generated by Django 5.2.12 on 2026-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("song_url", models.CharField(blank=True, max_length=500)),
                ("song_title_en", models.CharField(blank=True, max_length=500)),
                ("song_title_dn", models.CharField(blank=True, max_length=500)),
                ("singers", models.JSONField(blank=True, default=list)),
                ("music_directors", models.JSONField(blank=True, default=list)),
                ("actors", models.JSONField(blank=True, default=list)),
                ("lyricist", models.JSONField(blank=True, default=list)),
                ("album", models.CharField(blank=True, db_index=True, max_length=500)),
                (
                    "release_year",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("audio_url", models.CharField(blank=True, max_length=500)),
                ("video_url", models.CharField(blank=True, max_length=500)),
                ("lyrics_text_file", models.CharField(blank=True, max_length=500)),
                ("lyrics_image_file", models.CharField(blank=True, max_length=500)),
                ("lyrics_text_en", models.TextField(blank=True)),
                ("lyrics_text_dn", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
